In [1]:
import pandas as pd
import numpy as np

### 1

In [4]:
ratings = pd.read_csv('C://Users/Sudipta/Desktop/ML/acadgild/data/ml-20m/ratings.csv')
tags = pd.read_csv('C://Users/Sudipta/Desktop/ML/acadgild/data/ml-20m/tags.csv')
movies = pd.read_csv('C://Users/Sudipta/Desktop/ML/acadgild/data/ml-20m/movies.csv')

In [5]:
ratingsdf=ratings.head(1000)
tagsdf=tags.head(1000)
moviesdf=movies.head(1000)

### 2

In [6]:
type(tagsdf.head(1))

pandas.core.frame.DataFrame

## 3

#### Since I am selecting only 1000 records, I am printing 200 instead of 2000

In [16]:
tagsdf.loc[[0,11,200]]

     userId  movieId            tag   timestamp
0        18     4141    Mark Waters  1240597180
11       65     1783  noir thriller  1368149983
200     129    55280    dork people  1296939966

### 4

In [8]:
tagsdf.index

RangeIndex(start=0, stop=1000, step=1)

In [9]:
tagsdf.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [10]:
ratingsdf.index

RangeIndex(start=0, stop=1000, step=1)

In [13]:
ratingsdf.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [14]:
moviesdf.index

RangeIndex(start=0, stop=1000, step=1)

In [15]:
moviesdf.columns

Index(['movieId', 'title', 'genres'], dtype='object')

### 5

In [17]:
ratingsdf['rating'].describe()

count    1000.000000
mean        3.728000
std         0.923509
min         0.500000
25%         3.000000
50%         4.000000
75%         4.000000
max         5.000000
Name: rating, dtype: float64

### 6

#### Since I have selected 1000 records, not getting any output for rating > 5

In [22]:
ratingsdf[ratingsdf['rating'] > 4]

     userId  movieId  rating   timestamp
30        1     1196     4.5  1112484742
31        1     1198     4.5  1112484624
131       1     4993     5.0  1112484682
142       1     5952     5.0  1112484619
158       1     7153     5.0  1112484633
170       1     8507     5.0  1094786027
171       1     8636     4.5  1112485493
176       2       62     5.0   974820598
177       2       70     5.0   974820691
180       2      260     5.0   974821014
181       2      266     5.0   974820748
183       2      480     5.0   974820720
184       2      541     5.0   974821014
185       2      589     5.0   974820658
188       2      924     5.0   974821014
190       2     1196     5.0   974821014
191       2     1210     5.0   974820598
192       2     1214     5.0   974821014
193       2     1249     5.0   974820691
194       2     1259     5.0   974820659
195       2     1270     5.0   974821014
196       2     1327     5.0   974820846
197       2     1356     5.0   974820598
198       2     1544     5.0   974820943
201       2     1748     5.0   974821014
208       2     1974     5.0   974820598
215       2     2948     5.0   974820659
220       2     3450     5.0   974820846
221       2     3513     5.0   974820659
231       2     3927     5.0   974820748
..      ...      ...     ...         ...
881       8      593     5.0   833981896
883       8      597     5.0   833982889
885       8      648     5.0   834586915
888       9      858     5.0   994019177
892       9     1997     5.0   994020231
903       9     2959     5.0   994020680
906       9     3798     5.0   994020379
915       9     4148     5.0   994020180
927      10      527     5.0   943497122
928      10      858     5.0   943497439
938      10     1221     5.0   943497502
943      10     1247     5.0   943497554
946      10     1387     5.0   943497376
960      11        1     4.5  1230858821
963      11       32     5.0  1230783095
964      11       39     4.5  1230859032
968      11      150     5.0  1230785343
973      11      170     5.0  1230782534
974      11      172     5.0  1230787804
975      11      173     5.0  1230788954
977      11      208     4.5  1230787870
979      11      253     4.5  1230858996
980      11      256     5.0  1230788946
981      11      260     5.0  1230787560
985      11      318     5.0  1230850571
987      11      356     5.0  1230858804
991      11      380     5.0  1251170857
996      11      442     4.5  1230788002
997      11      480     5.0  1230788713
998      11      500     4.5  1230858949

[221 rows x 4 columns]

### 7

In [93]:
##ratingsdf.to_csv('C://Users/Sudipta/Desktop/ML/acadgild/data/ml-20m/ratings_null.csv')

In [97]:
ratings_withnull = pd.read_csv('C://Users/Sudipta/Desktop/ML/acadgild/data/ml-20m/ratings_null.csv')

In [103]:
ratings_withnull[ratings_withnull.isnull().any(axis=1)]

   userId  movieId  rating   timestamp
4       1       50     NaN  1112484580
5       1      112     NaN  1094785740
6       1      151     NaN  1094785734
7       1      223     NaN  1112485573
8       1      253     NaN  1112484940

In [106]:
ratings_withnull.isnull().sum()

userId       0
movieId      0
rating       5
timestamp    0
dtype: int64

In [108]:
ratings_withnull['rating'].fillna(ratings_withnull['rating'].mean())

0      3.500000
1      3.500000
2      3.500000
3      3.500000
4      3.727638
5      3.727638
6      3.727638
7      3.727638
8      3.727638
9      4.000000
10     4.000000
11     4.000000
12     4.000000
13     3.500000
14     3.500000
15     4.000000
16     3.500000
17     3.500000
18     3.000000
19     3.500000
20     3.500000
21     3.500000
22     4.000000
23     4.000000
24     3.500000
25     3.500000
26     4.000000
27     4.000000
28     3.500000
29     3.500000
         ...
970    4.000000
971    4.000000
972    4.000000
973    5.000000
974    5.000000
975    5.000000
976    4.000000
977    4.500000
978    4.000000
979    4.500000
980    5.000000
981    5.000000
982    0.500000
983    3.500000
984    3.500000
985    5.000000
986    3.500000
987    5.000000
988    4.000000
989    4.000000
990    4.000000
991    5.000000
992    3.500000
993    3.500000
994    4.000000
995    1.500000
996    4.500000
997    5.000000
998    4.500000
999    1.000000
Name: rating, dtype: float64

In [26]:
tagsdf[tagsdf.isnull().any(axis=1)]

Empty DataFrame
Columns: [userId, movieId, tag, timestamp]
Index: []

In [27]:
moviesdf[moviesdf.isnull().any(axis=1)]

Empty DataFrame
Columns: [movieId, title, genres]
Index: []

### 8

In [28]:
moviesdf[moviesdf['genres'].str.contains('Animation')]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
236,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
241,244,Gumby: The Movie (1995),Animation|Children
310,313,"Swan Princess, The (1994)",Animation|Children
360,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
547,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
553,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
582,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
588,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
589,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
590,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
604,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
610,616,"Aristocats, The (1970)",Animation|Children
624,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
653,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
664,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
697,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
708,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
728,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
732,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
770,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
871,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical

### 9

In [33]:
movie_rating=moviesdf.merge(ratingdf,on='movieId')
movie_rating['rating'].mean()

3.8232758620689653

### 10

In [35]:
moviesdf.set_index('movieId',inplace=True)

In [36]:
tagsdf.set_index('movieId',inplace=True)

In [37]:
moviesdf.join(tagsdf,how='inner')

,title,genres,userId,tag,timestamp
movieId,,,,,
32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,342,post-apocalyptic,1327514530
32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,342,psychology,1327514535
32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,342,time travel,1327514526
50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,342,organized crime,1328029111
50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,342,twist ending,1328029102
50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,342,twists & turns,1328029128
72,Kicking and Screaming (1995),Comedy|Drama,208,whit stillman meets Diner,1139110502
82,Antonia's Line (Antonia) (1995),Comedy|Drama,348,netflix,1313618543
104,Happy Gilmore (1996),Comedy,129,Adam Sandler,1297144668
104,Happy Gilmore (1996),Comedy,129,golf,1297144672
104,Happy Gilmore (1996),Comedy,129,sports,1297144670
208,Waterworld (1995),Action|Adventure|Sci-Fi,65,dark hero,1368150078
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,318,1970s,1424472169
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,318,fantasy,1424472169
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,318,sci-fi,1424472169
302,"Queen Margot (Reine Margot, La) (1994)",Drama|Romance,348,netflix,1226104039
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,friendship,1346540359
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,masterplan,1423424898
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,Morgan Freeman,1346540355
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,prison escape,1423424898
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,redemption,1423424898
318,"Shawshank Redemption, The (1994)",Crime|Drama,342,revenge,1346540367
340,"War, The (1994)",Adventure|Drama|War,359,Kevin Pederast,1191578282
353,"Crow, The (1994)",Action|Crime|Fantasy|Thriller,65,dark hero,1368150079
356,Forrest Gump (1994),Comedy|Drama|Romance|War,342,bittersweet,1346540428
356,Forrest Gump (1994),Comedy|Drama|Romance|War,342,classic,1346540434
356,Forrest Gump (1994),Comedy|Drama|Romance|War,342,vietnam war,1346540444
521,Romeo Is Bleeding (1993),Crime|Thriller,65,noir thriller,1368149983
571,"Wedding Gift, The (1994)",Drama|Romance,348,netflix,1297289290
592,Batman (1989),Action|Crime|Thriller,65,dark hero,1368150078
...,...,...,...,...,...
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,black comedy,1363561339
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,British,1363561329
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,cold war,1363561343
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,comedy,1363561345
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,Peter Sellers,1363561324
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,satire,1363561333
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,satirical,1363561332
750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,342,Stanley Kubrick,1363561313
778,Trainspotting (1996),Comedy|Crime|Drama,121,dark comedy,1300852846
778,Trainspotting (1996),Comedy|Crime|Drama,121,drugs,1300852844
778,Trainspotting (1996),Comedy|Crime|Drama,121,Nudity (Full Frontal - Notable),1300852839
778,Trainspotting (1996),Comedy|Crime|Drama,121,Nudity (Full Frontal),1300852841
898,"Philadelphia Story, The (1940)",Comedy|Drama|Romance,65,screwball comedy,1368150160
916,Roman Holiday (1953),Comedy|Drama|Romance,279,Audrey Hepburn,1329962461
916,Roman Holiday (1953),Comedy|Drama|Romance,279,black and white,1329962500
916,Roman Holiday (1953),Comedy|Drama|Romance,279,classic,1329962467
916,Roman Holiday (1953),Comedy|Drama|Romance,279,Gregory Peck,1329962459
916,Roman Holiday (1953),Comedy|Drama|Romance,279,imdb top 250,1329962478
916,Roman Holiday (1953),Comedy|Drama|Romance,279,Italy,1329962481
916,Roman Holiday (1953),Comedy|Drama|Romance,279,love story,1329962469
916,Roman Holiday (1953),Comedy|Drama|Romance,279,National Film Registry,1329962486
916,Roman Holiday (1953),Comedy|Drama|Romance,279,need to own,1329962471
916,Roman Holiday (1953),Comedy|Drama|Romance,279,romantic comedy,1329962476
916,Roman Holiday (1953),Comedy|Drama|Romance,279,Rome,1329962490
916,Roman Holiday (1953),Comedy|Drama|Romance,279,royalty,1329962474
916,Roman Holiday (1953),Comedy|Drama|Romance,279,slapstick,1329962495
916,Roman Holiday (1953),Comedy|Drama|Romance,279,zest for life,1329962497
930,Notorious (1946),Film-Noir|Romance|Thriller,348,oppl,1285879294
959,Of Human Bondage (1934),Drama,348,netflix,1262818612
974,Algiers (1938),Drama|Romance,348,own,1222462244

### 11

In [70]:
topmovies_comedy=movie_rating[(movie_rating['genres'].str.contains('Comedy')) & (movie_rating['rating'] > 4) ].title.unique()
for i in topmovies_comedy[0:5]:
    print(i)

Toy Story (1995)
Grumpier Old Men (1995)
Sabrina (1995)
American President, The (1995)
Clueless (1995)

### 12

In [71]:
moviesdf.genres.str.split('|',expand=True)

                 0          1         2         3         4     5
movieId
1        Adventure  Animation  Children    Comedy   Fantasy  None
2        Adventure   Children   Fantasy      None      None  None
3           Comedy    Romance      None      None      None  None
4           Comedy      Drama   Romance      None      None  None
5           Comedy       None      None      None      None  None
6           Action      Crime  Thriller      None      None  None
7           Comedy    Romance      None      None      None  None
8        Adventure   Children      None      None      None  None
9           Action       None      None      None      None  None
10          Action  Adventure  Thriller      None      None  None
11          Comedy      Drama   Romance      None      None  None
12          Comedy     Horror      None      None      None  None
13       Adventure  Animation  Children      None      None  None
14           Drama       None      None      None      None  None
15          Action  Adventure   Romance      None      None  None
16           Crime      Drama      None      None      None  None
17           Drama    Romance      None      None      None  None
18          Comedy       None      None      None      None  None
19          Comedy       None      None      None      None  None
20          Action     Comedy     Crime     Drama  Thriller  None
21          Comedy      Crime  Thriller      None      None  None
22           Crime      Drama    Horror   Mystery  Thriller  None
23          Action      Crime  Thriller      None      None  None
24           Drama     Sci-Fi      None      None      None  None
25           Drama    Romance      None      None      None  None
26           Drama       None      None      None      None  None
27        Children      Drama      None      None      None  None
28           Drama    Romance      None      None      None  None
29       Adventure      Drama   Fantasy   Mystery    Sci-Fi  None
30           Crime      Drama      None      None      None  None
...            ...        ...       ...       ...       ...   ...
988         Comedy      Drama      None      None      None  None
989          Drama       None      None      None      None  None
990         Action  Adventure  Thriller      None      None  None
991          Drama       None      None      None      None  None
992       Thriller       None      None      None      None  None
993          Drama       None      None      None      None  None
994         Comedy      Drama      None      None      None  None
996         Action      Crime     Drama  Thriller      None  None
997          Drama   Thriller      None      None      None  None
998         Action      Crime      None      None      None  None
999          Crime  Film-Noir      None      None      None  None
1000         Crime       None      None      None      None  None
1001        Comedy       None      None      None      None  None
1002        Comedy    Romance      None      None      None  None
1003         Drama   Thriller      None      None      None  None
1004        Action   Thriller      None      None      None  None
1005      Children     Comedy      None      None      None  None
1006         Drama       None      None      None      None  None
1007      Children     Comedy   Western      None      None  None
1008     Adventure    Western      None      None      None  None
1009     Adventure   Children   Fantasy      None      None  None
1010      Children     Comedy      None      None      None  None
1011     Adventure   Children    Comedy      None      None  None
1012      Children      Drama      None      None      None  None
1013      Children     Comedy   Romance      None      None  None
1014      Children     Comedy     Drama      None      None  None
1015     Adventure   Children     Drama      None      None  None
1016      Children     Comedy      None      None      None  None
1017     Adventure   Children      None      None      None  None
1018      Children     Comedy   Mystery      None      None  None

[1000 rows x 6 columns]

### 13

In [72]:
def getyear(str):
    start=str.index('(')
    end=str.index(')')
    return str[start+1:end]

In [73]:
moviesdf['year']=moviesdf.title.map(getyear)

C:\Users\Sudipta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [74]:
moviesdf.head()

,title,genres,year
movieId,,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
2,Jumanji (1995),Adventure|Children|Fantasy,1995
3,Grumpier Old Men (1995),Comedy|Romance,1995
4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
5,Father of the Bride Part II (1995),Comedy,1995

### 14

#### Since I hace selected first 1000 records, I have to change the date (2000-02-01) to get the results

In [81]:
import time as t

def tmconv(epoct):
    return t.strftime('%Y-%m-%d', t.localtime(epoct))

movie_rating['ts'] =movie_rating['timestamp'].map(tmconv)
movie_rating[movie_rating.ts > '2000-02-01']

,movieId,title,genres,userId,rating,timestamp,ts
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11,4.5,1230858821,2009-01-02
5,2,Jumanji (1995),Adventure|Children|Fantasy,1,3.5,1112486027,2005-04-03
7,3,Grumpier Old Men (1995),Comedy|Romance,2,4.0,974820889,2000-11-21
9,3,Grumpier Old Men (1995),Comedy|Romance,7,3.0,1011208463,2002-01-17
14,7,Sabrina (1995),Comedy|Romance,7,3.0,1011208220,2002-01-17
17,10,GoldenEye (1995),Action|Adventure|Thriller,11,2.5,1230858959,2009-01-02
19,11,"American President, The (1995)",Comedy|Drama|Romance,7,4.0,1011207889,2002-01-17
21,15,Cutthroat Island (1995),Action|Adventure|Romance,7,2.0,1011208732,2002-01-17
22,16,Casino (1995),Crime|Drama,7,3.0,1011205378,2002-01-16
25,17,Sense and Sensibility (1995),Drama|Romance,7,2.0,1011207676,2002-01-17
28,19,Ace Ventura: When Nature Calls (1995),Comedy,11,3.5,1230783704,2009-01-01
31,24,Powder (1995),Drama|Sci-Fi,7,3.0,1011207238,2002-01-17
33,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1,3.5,1112484676,2005-04-03
34,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,1,3.5,1112484819,2005-04-03
37,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,11,5.0,1230783095,2009-01-01
39,39,Clueless (1995),Comedy|Romance,11,4.5,1230859032,2009-01-02
40,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1,3.5,1112484727,2005-04-03
43,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1,3.5,1112484580,2005-04-03
47,62,Mr. Holland's Opus (1995),Drama,2,5.0,974820598,2000-11-21
50,65,Bio-Dome (1996),Comedy,11,2.0,1230856649,2009-01-02
51,70,From Dusk Till Dawn (1996),Action|Comedy|Horror|Thriller,2,5.0,974820691,2000-11-21
53,105,"Bridges of Madison County, The (1995)",Drama|Romance,7,2.0,1011208366,2002-01-17
54,110,Braveheart (1995),Action|Drama|War,2,4.0,974820658,2000-11-21
57,110,Braveheart (1995),Action|Drama|War,11,4.0,1230853748,2009-01-02
58,112,Rumble in the Bronx (Hont faan kui) (1995),Action|Adventure|Comedy|Crime,1,3.5,1094785740,2004-09-10
59,122,Boomerang (1992),Comedy|Romance,7,2.0,1011208569,2002-01-17
65,145,Bad Boys (1995),Action|Comedy|Crime|Drama|Thriller,11,3.0,1230785947,2009-01-01
68,150,Apollo 13 (1995),Adventure|Drama|IMAX,11,5.0,1230785343,2009-01-01
69,151,Rob Roy (1995),Action|Drama|Romance|War,1,4.0,1094785734,2004-09-10
70,151,Rob Roy (1995),Action|Drama|Romance|War,7,3.0,1011207965,2002-01-17
...,...,...,...,...,...,...,...
269,593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1,3.5,1112484661,2005-04-03
278,597,Pretty Woman (1990),Comedy|Romance,7,4.0,1011207938,2002-01-17
288,653,Dragonheart (1996),Action|Adventure|Fantasy,1,3.0,1094785691,2004-09-10
291,674,Barbarella (1968),Adventure|Comedy|Sci-Fi,7,2.0,1011207238,2002-01-17
294,708,"Truth About Cats & Dogs, The (1996)",Comedy|Romance,7,3.0,1011208066,2002-01-17
303,736,Twister (1996),Action|Adventure|Romance|Thriller,7,3.0,1011208161,2002-01-17
305,750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,7,5.0,1011206659,2002-01-17
310,780,Independence Day (a.k.a. ID4) (1996),Action|Adventure|Sci-Fi|Thriller,7,4.0,1011206898,2002-01-17
314,788,"Nutty Professor, The (1996)",Comedy|Fantasy|Romance|Sci-Fi,7,3.0,1011208527,2002-01-17
316,806,American Buffalo (1996),Crime|Drama,7,1.0,1011206295,2002-01-17
318,852,Tin Cup (1996),Comedy|Drama|Romance,7,3.0,1011207889,2002-01-17
320,858,"Godfather, The (1972)",Crime|Drama,9,5.0,994019177,2001-07-02
322,880,"Island of Dr. Moreau, The (1996)",Sci-Fi|Thriller,7,3.0,1011207270,2002-01-17
323,891,Halloween: The Curse of Michael Myers (Hallowe...,Horror|Thriller,2,2.0,974820969,2000-11-21
324,899,Singin' in the Rain (1952),Comedy|Musical|Romance,7,4.0,1011207810,2002-01-17
327,908,North by Northwest (1959),Action|Adventure|Mystery|Romance|Thriller,2,4.0,974820691,2000-11-21
328,908,North by Northwest (1959),Action|Adventure|Mystery|Romance|Thriller,7,4.0,1011204510,2002-01-16
329,912,Casablanca (1942),Drama|Romance,7,5.0,1011204596,2002-01-16
331,914,My Fair Lady (1964),Comedy|Drama|Musical|Romance,7,3.0,1011207916,2002-01-17
332,919,"Wizard of Oz, The (1939)",Adventure|Children|Fantasy|Musical,1,3.5,1094785621,2004-09-10
334,920,Gone with the Wind (1939),Drama|Romance|War,7,4.0,1011207700,2002-01-17
335,922,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),Drama|Film-Noir|Romance,7,3.0,1011207570,2002-01-17
336,924,2001: A Space Odyssey (1968),Adventure|Drama|Sci-Fi,1,3.5,1094785598,2004-09-10
337,924,2001: A Space Odyssey (1968),Adventure|Drama|Sci-Fi,2,5.0,974821014,2000-11-21
339,924,2001: A Space Odyssey (1968),Adventure|Drama|Sci-Fi,7,3.0,1011206698,2002-01-17
340,928,Rebecca (1940),Drama|Mystery|Romance|Thriller,7,3.0,1011207775,2002-01-17
341,932,"Affair to Remember, An (1957)",Drama|Romance,7,3.0,1011207830,2002-01-17
342,952,Around the World in 80 Days (1956),Adventure|Comedy,7,3.0,1011206498,2002-01-17
346,1009,Escape to Witch Mountain (1975),Adventure|Children|Fantasy,1,3.5,1112486013,2005-04-03
347,1017,Swiss Family Robinson (1960),Adventure|Children,7,4.0,1011205481,2002-01-16

### 15

In [82]:
tagsdf['ts'] = tagsdf['timestamp'].map(tmconv)

C:\Users\Sudipta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [89]:
tagsdf.sort_index(by='ts',ascending=False)

C:\Users\Sudipta\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':

,userId,tag,timestamp,ts
movieId,,,,
108190,342,dystopia,1426978076,2015-03-22
108190,342,based on a book,1426978115,2015-03-22
260,318,1970s,1424472169,2015-02-21
260,318,fantasy,1424472169,2015-02-21
260,318,sci-fi,1424472169,2015-02-21
115149,318,Action,1424534310,2015-02-21
115149,318,Revenge,1424534283,2015-02-21
115149,318,Willem Dafoe,1424534383,2015-02-21
318,342,redemption,1423424898,2015-02-09
318,342,prison escape,1423424898,2015-02-09
318,342,masterplan,1423424898,2015-02-09
89118,342,spanish,1422734293,2015-02-01
112556,342,unpredictable,1422733885,2015-02-01
54372,342,French,1422734628,2015-02-01
54372,342,murder mystery,1422734632,2015-02-01
112556,342,based on a book,1422733895,2015-02-01
112556,342,marriage,1422733850,2015-02-01
112556,342,meticulous,1422733882,2015-02-01
112556,342,Neal Patrick Harris,1422733874,2015-02-01
112556,342,mindfuck,1422733866,2015-02-01
89118,342,long revenge,1422734239,2015-02-01
54372,342,twist ending,1422734630,2015-02-01
89118,342,unpredictable,1422734224,2015-02-01
89118,342,disturbing,1422734236,2015-02-01
99114,342,slavery,1415478601,2014-11-09
99114,342,Samuel L. Jackson,1415478605,2014-11-09
99114,342,Quentin Tarantino,1415478596,2014-11-09
99114,342,Over the top,1415478587,2014-11-09
99114,342,Leonardo DiCaprio,1415478599,2014-11-09
31410,342,World War II,1415479140,2014-11-09
...,...,...,...,...
45062,359,Obviously Hillary Had A Different Meaning For ...,1148352677,2006-05-23
4978,359,The Mother Of Connect-The-Dots Flix (Grand Ca...,1148369277,2006-05-23
37853,359,Millions Of Dollars In Drugs Or One Hot Girlfr...,1148369786,2006-05-23
37857,359,No Wonder Carneys Love The Life,1148370339,2006-05-23
39414,359,Steve Martin Is Scraping The Bottom HARD!,1146301137,2006-04-29
2502,320,must show,1145964798,2006-04-25
1197,320,must show,1145964801,2006-04-25
1396,320,must show,1145964810,2006-04-25
2011,320,must show,1145964858,2006-04-25
2012,320,must show,1145964915,2006-04-25
2762,320,twist,1145964832,2006-04-25
7438,320,violent,1145964764,2006-04-25
6016,320,violent,1145964670,2006-04-25
3996,320,overrated,1145964748,2006-04-25
2959,320,twist,1145964658,2006-04-25
43928,359,Read All The Negative Reviews & Save 2 Hours O...,1141692018,2006-03-07
6294,359,With A Name Like Chew Yer Fat A Crossover Is N...,1141047000,2006-02-27
34542,359,Never Ever Discuss Your Lack Of Game To Wild B...,1140487310,2006-02-21
36529,359,I Don't Think Arms Dealers Look Anything Like ...,1140486341,2006-02-21
35957,359,Never Trust Euro-Looking A-Holes @ The Airport...,1140487180,2006-02-21
37729,359,Tim Burton Hits Another One Out Of The Cemetery,1140486102,2006-02-21
34271,359,We All Gotta Have A Dream,1140487034,2006-02-21
37380,359,Half-Assed Productions,1140485781,2006-02-21
36537,359,Teen Induced Angst Overdose,1140486260,2006-02-21
8645,208,too upper class,1139761704,2006-02-12
8645,208,actress too old,1139761704,2006-02-12
27727,208,wild and fresh,1139177085,2006-02-06
40819,208,whit stillman meets diner,1139110430,2006-02-05
72,208,whit stillman meets Diner,1139110502,2006-02-05
41573,208,utterly predictable ensemble flick,1137445827,2006-01-17

In [90]:
tagsdf.sort_values(by='ts',ascending=False)

,userId,tag,timestamp,ts
movieId,,,,
108190,342,dystopia,1426978076,2015-03-22
108190,342,based on a book,1426978115,2015-03-22
260,318,1970s,1424472169,2015-02-21
260,318,fantasy,1424472169,2015-02-21
260,318,sci-fi,1424472169,2015-02-21
115149,318,Action,1424534310,2015-02-21
115149,318,Revenge,1424534283,2015-02-21
115149,318,Willem Dafoe,1424534383,2015-02-21
318,342,redemption,1423424898,2015-02-09
318,342,prison escape,1423424898,2015-02-09
318,342,masterplan,1423424898,2015-02-09
89118,342,spanish,1422734293,2015-02-01
112556,342,unpredictable,1422733885,2015-02-01
54372,342,French,1422734628,2015-02-01
54372,342,murder mystery,1422734632,2015-02-01
112556,342,based on a book,1422733895,2015-02-01
112556,342,marriage,1422733850,2015-02-01
112556,342,meticulous,1422733882,2015-02-01
112556,342,Neal Patrick Harris,1422733874,2015-02-01
112556,342,mindfuck,1422733866,2015-02-01
89118,342,long revenge,1422734239,2015-02-01
54372,342,twist ending,1422734630,2015-02-01
89118,342,unpredictable,1422734224,2015-02-01
89118,342,disturbing,1422734236,2015-02-01
99114,342,slavery,1415478601,2014-11-09
99114,342,Samuel L. Jackson,1415478605,2014-11-09
99114,342,Quentin Tarantino,1415478596,2014-11-09
99114,342,Over the top,1415478587,2014-11-09
99114,342,Leonardo DiCaprio,1415478599,2014-11-09
31410,342,World War II,1415479140,2014-11-09
...,...,...,...,...
45062,359,Obviously Hillary Had A Different Meaning For ...,1148352677,2006-05-23
4978,359,The Mother Of Connect-The-Dots Flix (Grand Ca...,1148369277,2006-05-23
37853,359,Millions Of Dollars In Drugs Or One Hot Girlfr...,1148369786,2006-05-23
37857,359,No Wonder Carneys Love The Life,1148370339,2006-05-23
39414,359,Steve Martin Is Scraping The Bottom HARD!,1146301137,2006-04-29
2502,320,must show,1145964798,2006-04-25
1197,320,must show,1145964801,2006-04-25
1396,320,must show,1145964810,2006-04-25
2011,320,must show,1145964858,2006-04-25
2012,320,must show,1145964915,2006-04-25
2762,320,twist,1145964832,2006-04-25
7438,320,violent,1145964764,2006-04-25
6016,320,violent,1145964670,2006-04-25
3996,320,overrated,1145964748,2006-04-25
2959,320,twist,1145964658,2006-04-25
43928,359,Read All The Negative Reviews & Save 2 Hours O...,1141692018,2006-03-07
6294,359,With A Name Like Chew Yer Fat A Crossover Is N...,1141047000,2006-02-27
34542,359,Never Ever Discuss Your Lack Of Game To Wild B...,1140487310,2006-02-21
36529,359,I Don't Think Arms Dealers Look Anything Like ...,1140486341,2006-02-21
35957,359,Never Trust Euro-Looking A-Holes @ The Airport...,1140487180,2006-02-21
37729,359,Tim Burton Hits Another One Out Of The Cemetery,1140486102,2006-02-21
34271,359,We All Gotta Have A Dream,1140487034,2006-02-21
37380,359,Half-Assed Productions,1140485781,2006-02-21
36537,359,Teen Induced Angst Overdose,1140486260,2006-02-21
8645,208,too upper class,1139761704,2006-02-12
8645,208,actress too old,1139761704,2006-02-12
27727,208,wild and fresh,1139177085,2006-02-06
40819,208,whit stillman meets diner,1139110430,2006-02-05
72,208,whit stillman meets Diner,1139110502,2006-02-05
41573,208,utterly predictable ensemble flick,1137445827,2006-01-17